---
permalink: intro-family.html 
keywords: introduction, how astra works, how Astra works, what Astra is, astra control, kubernetes, astra control service, astra control center 
summary: Astra ist ein Kubernetes-Managementservice für Applikationsdaten, der den Betrieb zustandsorientierte Applikationen vereinfacht. Schutz, Backup und Migration von Kubernetes-Workloads und sofortige Erstellung von Applikationsklonen 
---
= Erfahren Sie mehr über die Astra Produktfamilie
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Die NetApp Astra Produktfamilie bietet Management von Applikationsdaten und Storage für Cloud-native Applikationen.

Die Lösungen von Astra umfassen:

* *Astra Control*: Nutzen Sie applikationsorientierte Datenmanagement-Tools, mit denen Sie Kubernetes-Workloads sowohl in Public Clouds als auch in On-Premises-Umgebungen managen, sichern und verschieben können.​
+
** *Astra Control Service*: Nutzen Sie einen von NetApp gemanagten Service für das Datenmanagement von Kubernetes-Workloads in Public Clouds.
** *Astra Control Center*: Nutzen Sie eigenständige Software für das Datenmanagement lokaler Kubernetes Workloads.


* *Astra Trident*: Verwenden Sie mit NetApp Storage-Providern Container-Storage-Interface (CSI)-kompatible Storage-Bereitstellung und -Management für Kubernetes-Workloads.




== Astra Control

Astra Control ist eine Kubernetes-Lösung für das Lifecycle-Management von Applikationsdaten, die den Betrieb zustandsorientierte Applikationen vereinfacht. Schutz, Backup und Migration von Kubernetes-Workloads und sofortige Erstellung von Applikationsklonen



=== Funktionen

Astra Control bietet entscheidende Funktionen für das Lifecycle Management von Kubernetes-Applikationsdaten:

* Automatisches Management von persistentem Storage
* Erstellen Sie applikationsorientierte Snapshots und Backups nach Bedarf
* Automatisierung von richtlinienbasierten Snapshot- und Backup-Vorgängen
* Migrieren Sie Applikationen und Daten von einem Kubernetes-Cluster zu einem anderen
* Replizieren von Applikationen auf ein Remote-System mit NetApp SnapMirror Technologie (Astra Control Center)
* Klonen von Applikationen von Staging hin zur Produktion
* Darstellung des Anwendungszustands und des Schutzstatus
* Verwenden Sie eine Web-Oberfläche oder eine API zur Implementierung Ihrer Backup- und Migration-Workflows




=== Implementierungsmodelle

Astra Control ist in zwei Implementierungsmodellen erhältlich:

* *Astra Control Service*: Ein von NetApp gemanagter Service, der applikationskonsistentes Datenmanagement für Kubernetes-Cluster in Umgebungen mehrerer Cloud-Provider sowie selbstverwaltete Kubernetes-Cluster bietet.
+
https://docs.netapp.com/us-en/astra/index.html["Dokumentation des Astra Control Service"^]

* *Astra Control Center*: Gemanagte Software für applikationsgerechtes Datenmanagement von Kubernetes-Clustern, die in Ihrer On-Premises-Umgebung ausgeführt werden. Astra Control Center kann auch auf mehreren Cloud-Provider-Umgebungen mit einem NetApp Cloud Volumes ONTAP Storage-Backend installiert werden.
+
https://docs.netapp.com/us-en/astra-control-center/["Astra Control Center-Dokumentation"^]



[cols="1h,2a,2a"]
|===
|  | Astra Control Service | Astra Control Center 


| Wie wird das angeboten?  a| 
Vollständig gemanagter Cloud-Service von NetApp
 a| 
Als Software, die Sie herunterladen, installieren und verwalten



| Wo wird sie gehostet?  a| 
In einer Public Cloud von NetApp ihrer Wahl
 a| 
In Ihrem eigenen Kubernetes-Cluster



| Wie wird sie aktualisiert?  a| 
Gemanagt von NetApp
 a| 
Sie verwalten jegliche Updates



| Was ist die Back-End-Unterstützung für Storage?  a| 
* Amazon Web Services:
+
** Amazon EBS
** Amazon FSX für NetApp ONTAP
** link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws.html["Cloud Volumes ONTAP"^]


* Google Cloud:
+
** Google Persistent Disk
** NetApp Cloud Volumes Service
** link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html["Cloud Volumes ONTAP"^]


* Microsoft Azure:
+
** Über Azure Gemanagte Festplatten
** Azure NetApp Dateien
** link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-azure.html["Cloud Volumes ONTAP"^]


* Self-Managed Cluster:
+
** Amazon EBS
** Google Persistent Disk
** Über Azure Gemanagte Festplatten
** link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-overview-cvo.html["Cloud Volumes ONTAP"^]



 a| 
* NetApp ONTAP AFF und FAS Systeme
* link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-overview-cvo.html["Cloud Volumes ONTAP"^]


|===


== Astra Trident

Astra Trident ist die Open-Source-Implementierung einer driver​ Kubernetes Container Storage Interface (CSI) von NetApp. Astra Trident bietet Orchestrierung und Datenkonnektivität für Kubernetes applications​.

https://docs.netapp.com/us-en/trident/index.html["Astra Trident-Dokumentation"^]



== Finden Sie weitere Informationen

* https://docs.netapp.com/us-en/astra/index.html["Dokumentation des Astra Control Service"^]
* https://docs.netapp.com/us-en/astra-control-center/["Astra Control Center-Dokumentation"^]
* https://docs.netapp.com/us-en/trident/index.html["Astra Trident-Dokumentation"^]
* https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^]
* https://docs.netapp.com/us-en/cloudinsights/["Cloud Insights-Dokumentation"^]
* https://docs.netapp.com/us-en/ontap/index.html["ONTAP-Dokumentation"^]

