---
permalink: intro-family.html 
keywords: introduction, how astra works, how Astra works, what Astra is, astra control, kubernetes, astra control service, astra control center 
summary: Astra ist ein Kubernetes-Managementservice für Applikationsdaten, der den Betrieb zustandsorientierte Applikationen vereinfacht. Schutz, Backup und Migration von Kubernetes-Workloads und sofortige Erstellung von Applikationsklonen 
---
= Weitere Informationen zu Astra Control
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Astra Control ist eine Lösung zur Verwaltung des Lebenszyklus von Anwendungsdaten in Kubernetes, die den Betrieb von Anwendungen mit Status vereinfacht und Ihnen hilft, Ihre Kubernetes-Workloads in hybriden Umgebungen zu speichern, zu schützen und zu verschieben.



== Sorgen

Astra Control bietet entscheidende Funktionen für das Lifecycle Management von Kubernetes-Applikationsdaten:

*Store*:

* Dynamische Storage-Bereitstellung für Container-Workloads
* Verschlüsselung der Daten auf der Übertragungsstrecke aus Container zu persistenten Volumes
* Regionsübergreifende, zonenübergreifende Replizierung


*Schutz*:

* Automatische Erkennung und applikationsgerechte Sicherung einer gesamten Applikation und ihrer Daten
* Sofortige Wiederherstellung einer Applikation von einer beliebigen Snapshot-Version je nach den Anforderungen Ihres Unternehmens
* Schnelles Failover über Zonen, Regionen und Cloud-Provider hinweg


*Verschieben*:

* Vollständige Applikations- und Datenmobilität innerhalb und zwischen Kubernetes-Clustern und Clouds
* Sofortige Klone vollständiger Applikationen und Daten
* Migration von Anwendungen mit einem Klick über eine konsistente Web-UI und -API




== Der Netapp Architektur Sind

Mit der Architektur von Astra Control bietet die IT erweiterte Datenmanagementfunktionen, die sowohl die Funktionalität als auch die Verfügbarkeit von Kubernetes-Applikationen verbessern. Sie vereinfacht das Management, den Schutz und die Verschiebung von Container-Workloads in Public Clouds und On-Premises-Umgebungen. die Software bietet Automatisierungsfunktionen über ihre REST-API und sein SDK und ermöglicht einen programmatischen Zugriff für eine nahtlose Integration in vorhandene Workflows.

Astra Control ist Kubernetes-nativ und ermöglicht Datensicherungs-Workflows, die benutzerdefinierte Ressourcen verwenden und gleichzeitig rückwärtskompatibel mit der vorhandenen API und dem SDK bleiben. Die native Datensicherung von Kubernetes bietet deutliche Vorteile. Durch die nahtlose Integration in Kubernetes-APIs und -Ressourcen kann die Datensicherung über die vorhandenen CI/CD- und/oder GitOps-Tools eines Unternehmens zu einem integrierenden Bestandteil des Applikationslebenszyklus werden.

Astra Control basiert auf vier sich ergänzenden Komponenten:

* *Astra Control*: Astra Control ist der zentralisierte Verwaltungsdienst für alle verwalteten Cluster und bietet orchestrierte Workloads für Anwendungsschutz und Mobilität vor Ort sowie die folgenden Funktionen:
+
** Kombinierte Ansicht mehrerer Cluster
** Schutz orchestrierter Workflows
** Granulare Ressourcenvisualisierung und -Auswahl


* *Astra Connector*: Astra Connector arbeitet mit Astra Control zusammen, um eine sichere Verbindung zu jedem verwalteten Cluster bereitzustellen und so die lokale Ausführung geplanter Operationen unabhängig vom Verbindungsstatus sowie die folgenden Funktionen zu ermöglichen:
+
** Lokale Ausführung geplanter Vorgänge unabhängig vom Verbindungsstatus
** Lokale Abläufe, die die Nutzung von Astra Systemressourcen auf Cluster verteilen und optimieren
** Lokale Installation, die den Zugriff auf das Cluster mit den geringsten Berechtigungen ermöglicht, um die Sicherheit zu erhöhen


* *Astra Control Provisioner*: Der Astra Control Provisioner bietet zentrale CSI-Bereitstellungsfunktionen und erweiterte Storage Management-Funktionen für zusätzliche Sicherheit und Disaster Recovery-Konfiguration sowie die folgenden Funktionen:
+
** Dynamische Storage-Bereitstellung für Container-Workloads
** Erweitertes Storage-Management:
+
*** Verschlüsselung der Daten während der Übertragung vom Container zum PV
*** SnapMirror Cloud Funktionalität mit regionsübergreifender Replizierung




* *Astra Custom-Ressourcen*: Auf jedem Cluster verwendete benutzerdefinierte Ressourcen bieten einen Kubernetes-nativen Ansatz für die lokale Ausführung von Vorgängen. Dies vereinfacht die Integration in andere Kubernetes-freundliche Tools und Automatisierungsfunktionen sowie folgende Funktionen:
+
** Direkte Integration und Workflows für die Automatisierung von Tools anderer Anbieter
** Primitive auf niedrigerer Ebene, die benutzerdefinierte Workflows ermöglichen






== Implementierungsmodelle

Astra Control ist in einem einzigen Bereitstellungsmodell verfügbar.

*Astra Control Center*: Gemanagte Software für applikationsgerechtes Datenmanagement von Kubernetes-Clustern, die in Ihrer On-Premises-Umgebung ausgeführt werden. Astra Control Center kann auch auf mehreren Cloud-Provider-Umgebungen mit einem NetApp Cloud Volumes ONTAP Storage-Backend installiert werden.

https://docs.netapp.com/us-en/astra-control-center/["Astra Control Center-Dokumentation"^]

[cols="1h,2d"]
|===
|  | Astra Control Center 


| Wie wird das angeboten? | Als Software, die Sie herunterladen, installieren und verwalten können 


| Wo wird sie gehostet? | In Ihrem eigenen Kubernetes-Cluster 


| Wie wird sie aktualisiert? | Sie verwalten jegliche Updates 


| Welche Kubernetes-Distributionen werden unterstützt?  a| 
* Azure Kubernetes Service für Azure Stack HCI
* Google Anthos
* Kubernetes (Vorgelagert)
* Rancher Kubernetes Engine (RKE)
* Red hat OpenShift Container Platform




| Welche Storage-Back-Ends werden unterstützt?  a| 
* NetApp ONTAP AFF und FAS Systeme
* NetApp ONTAP Select
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/["Cloud Volumes ONTAP"^]
* https://longhorn.io/["Longhorn"^]


|===


== Finden Sie weitere Informationen

* https://docs.netapp.com/us-en/astra-control-center/["Astra Control Center-Dokumentation"^]
* https://docs.netapp.com/us-en/trident/index.html["Astra Trident-Dokumentation"^]
* https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^]
* https://docs.netapp.com/us-en/cloudinsights/["Cloud Insights-Dokumentation"^]
* https://docs.netapp.com/us-en/ontap/index.html["ONTAP-Dokumentation"^]

