---
settings:
  name: Astra Family
  search: astra-control-center,astra-automation,trident
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Dokumentation der Astra Produktfamilie
    url: "/index.html"
